// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LionPetManagement_Entities.Models;

[Table("LionProfile")]
public partial class LionProfile
{
    [Key]
    public int LionProfileId { get; set; }

    public int LionTypeId { get; set; }

    [Required]
    [StringLength(150)]
    public string LionName { get; set; }

    public double Weight { get; set; }

    [Required]
    [StringLength(2000)]
    public string Characteristics { get; set; }

    [Required]
    [StringLength(1500)]
    public string Warning { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [ForeignKey("LionTypeId")]
    [InverseProperty("LionProfiles")]
    public virtual LionType LionType { get; set; }
}