// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChargingManagement.Entities.Models;

public partial class ChargingStation
{
    public int StationId { get; set; }

    public string StationName { get; set; }

    public string Location { get; set; }

    public decimal? MaxPower { get; set; }

    public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
}