// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ChargingManagement.Entities.Models;

public partial class ChargingSession : IValidatableObject
{
    public int SessionId { get; set; }

    [Required(ErrorMessage = "Station is required.")]
    public int StationId { get; set; }

    [Required(ErrorMessage = "Driver is required.")]
    public int DriverId { get; set; }

    [Required(ErrorMessage = "Start Time is required.")]
    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    [Required(ErrorMessage = "KWh Consumed is required.")]
    [Range(0.001, double.MaxValue, ErrorMessage = "KWh Consumed must be a positive number (greater than 0).")]
    public decimal KwhConsumed { get; set; }

    [Required(ErrorMessage = "Cost is required.")]
    [Range(1000.01, double.MaxValue, ErrorMessage = "Cost must be greater than 1000.")]
    public decimal Cost { get; set; }

    public virtual SystemUser Driver { get; set; }

    public virtual ChargingStation Station { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Start Time cannot be future date
        if (StartTime >= DateTime.Now)
        {
            yield return new ValidationResult(
                "Start Time cannot be a future date.",
                new[] { nameof(StartTime) });
        }

        // End Time validations
        if (EndTime.HasValue)
        {
            if (EndTime >= DateTime.Now)
            {
                yield return new ValidationResult(
                    "End Time cannot be a future date.",
                    new[] { nameof(EndTime) });
            }

            if (EndTime <= StartTime)
            {
                yield return new ValidationResult(
                    "End Time must be after the Start Time.",
                    new[] { nameof(EndTime) });
            }
        }
    }
}