// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChargingManagement.Entities.Models;

public partial class SystemUser
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string UserPassword { get; set; }

    public int UserRole { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
}