// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FFHRRequestSystem.Entitites.VietN.Models;

public partial class ProcessingTypeVietN
{
    public int ProcessingTypeVietNid { get; set; }

    public string TypeName { get; set; }

    public string TypeCode { get; set; }

    public string Description { get; set; }

    public bool RequireApproval { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<TicketProcessingVietN> TicketProcessingVietNs { get; set; } = new List<TicketProcessingVietN>();
}