// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RealEstateManagement.Entities.Models;

public partial class Contract
{
    public int ContractId { get; set; }
    [Required(ErrorMessage = "required")]
  
    public string ContractTitle { get; set; }
    [Required(ErrorMessage = "required")]

    public string PropertyType { get; set; }

    public DateOnly SigningDate { get; set; }
    [Required(ErrorMessage = "required")]

    public DateOnly ExpirationDate { get; set; }

    public int BrokerId { get; set; }
    [Required(ErrorMessage = "required")]

    public decimal Value { get; set; }

    public virtual Broker Broker { get; set; }
}