// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LionPetManagement.Entities.Models;


[Table("LionProfile")]
public partial class LionProfile
{
    [Key]
    public int LionProfileId { get; set; }

    [Required(ErrorMessage = "LionTypeId is required")]
    [Display(Name = "Lion Type")]
    public int LionTypeId { get; set; }

    [Required(ErrorMessage = "LionName is required")]
    [StringLength(150)]
    [MinLength(4, ErrorMessage = "LionName must be at least 4 characters")]
    [RegularExpression(@"^(?!.*[#@&()])[A-Z][a-zA-Z]*(\s+[A-Z][a-zA-Z]*)*$",
        ErrorMessage = "LionName must not contain special characters (#, @, &, (, )) and each word must start with a capital letter")]
    [Display(Name = "Lion Name")]
    public string LionName { get; set; }

    [Required(ErrorMessage = "Weight is required")]
    [Range(30.1, double.MaxValue, ErrorMessage = "Weight must be greater than 30")]
    public double Weight { get; set; }

    [Required(ErrorMessage = "Characteristics is required")]
    [StringLength(2000)]
    public string Characteristics { get; set; }

    [Required(ErrorMessage = "Warning is required")]
    [StringLength(1500)]
    public string Warning { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [ForeignKey("LionTypeId")]
    [InverseProperty("LionProfiles")]
    public virtual LionType LionType { get; set; }
}