// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FFHRRequestSystem.Entitites.VietN.Models;

public partial class TicketProcessingVietN
{
    public Guid TicketProcessingVietNid { get; set; }

    public string ProcessingCode { get; set; }

    public string TicketReference { get; set; }

    public int? ProcessingTypeVietNid { get; set; }

    public string ProcessingAction { get; set; }

    public string ActionDescription { get; set; }

    public string RelatedTicketCode { get; set; }

    public int PriorityLevel { get; set; }

    public int Status { get; set; }

    public decimal? OverdueDays { get; set; }

    public int? EscalationLevel { get; set; }

    public bool IsAutoProcessed { get; set; }

    public string ProcessedBy { get; set; }

    public DateTime? ProcessedDate { get; set; }

    public string ResolvedNote { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ProcessingTypeVietN ProcessingTypeVietN { get; set; }
}